version: '3.4'

services:
  nosql:
    ports:
    - '27017:27017'
    container_name: mongodb
    restart: always
    logging:
        options:
            max-size: 1g
    volumes:
        - mongodb_data:/data/db
    image: mongo

  emotectmemo:
    image: ${DOCKER_REGISTRY-}emotectmemo
    container_name: emotectmemo
    restart: always
    build:
      context: .
      dockerfile: EmotectMemo/Dockerfile
    environment:
      ASPNETCORE_HTTP_PORTS: "8080"
    depends_on:
      - nosql
    ports:
      - "62000:8080"

  emotectmemosite:
    ports:
    - '9090:80'
    image: ${DOCKER_REGISTRY-}emotectmemosite
    container_name: emotectmemo-site
    restart: always
    build:
      no_cache: true
      context: .
      dockerfile: EmotectMemo.UI/Dockerfile
      args:
        - EMOTECTAPI=http://localhost:62000

volumes:
  mongodb_data:
